#!/usr/bin/env bash

case $1 in
  db)
    bash s/db_helper.sh $2
    ;;

  db-init)
    bash s/db_helper.sh init-1
    bash s/db_helper.sh init-2
    bash s/db_helper.sh init-3
    bash s/db_helper.sh init-4
    bash s/db_helper.sh init-5
    ;;

  db-seed)
    bash s/db_helper.sh seed
    ;;
  dc-up | dc-u)
    echo "Starting docker for the database"
    docker-compose up
    ;;
  dc-down | dc-d)
    docker-compose down
    ;;
  lint | l)
    bash s/lint_helper.sh $2
    ;;
  frontend | front | f | client | c)
    echo "Starting client/frontend for development"
    cd client && npm run start
    ;;
  server | s)
    echo "Starting the server for development"
    cd server && npm run dev:server
    ;;
  help | h)
    bash s/help_center.sh $2
    ;;
  *)
    echo 'To get help, please run `s/run help` or `s/run h` that invokes `s/help_center.sh`'
    echo '`s/help_center.sh` and this file (`s/run`) can also be viewed manually'
    ;;
esac
